### ISSUE TITLE
Set up Travis CI

### ISSUE THREAD

**Issue by ysitu** [networkx/networkx-metis#12]
Run `nose` and `pylint`; `coverage` is optional.

**Comment by OrkoHunter** [comment]
Can you please adjust the due date of the [milestone](https://github.com/networkx/networkx-metis/milestones/networkx-metis-1.0) with the release of NetworkX 2.0?

**Comment by ysitu** [comment]
I have change the milestone for networkx-metis 1.0 to Jul 8. I am thinking that maybe we should cherrypick networkx/networkx#1595 into the 1.10 so that we do not have to wait till release of networkx 2.0, which will be after end of GSoC, before releasing networkx-metis.

**Comment by chebee7i** [comment]
I'd be okay with that! It is a minimal change to NetworkX.

**Comment by OrkoHunter** [comment]
Do we have to run `pylint` in the `script` of .travis.yml ?

**Comment by OrkoHunter** [comment]
If not, can we let #16 in and one of the collaborators set up the hook on travis-ci.org ?

**Comment by ysitu** [comment]
We should run `pylint`. It catches more than style errors.

**Comment by OrkoHunter** [comment]
Okay... All I need is just to add `pylint *` in the `script` section?

**Comment by ysitu** [comment]
Use `pylint networkx.addons.metis`.

**Comment by OrkoHunter** [comment]
@dschult @jtorrents @hagberg May one of you please set up the hook on [travis-ci.org](travis-ci.org/networkx/networkx-metis) for this repository?
