### ISSUE TITLE
Change test_metis.py to test the exposed functions

### ISSUE THREAD

**Issue by ysitu** [networkx/networkx-metis#26]
We should not be directly testing functions from `_metis.pyx` as those are implementation detail.

**Comment by OrkoHunter** [comment]
Okay.. So rather we'd be testing the functions in the top level of `networkx.addons.metis`.

**Comment by ysitu** [comment]
That is about the philosophy of testing. Impose constraints on only the public interfaces so that you are handcuffed to the implementation details.

**Comment by ysitu** [comment]
@OrkoHunter Can you prioritize this?

**Comment by OrkoHunter** [comment]
Sure. This is a must. I'll be sending a PR shortly.
