### ISSUE TITLE
Setting up hooks for `networkx-metis` on travis-ci.org and landscape.io

### ISSUE THREAD

**Issue by OrkoHunter** [networkx/networkx-metis#28]
@hagberg @dschult @jtorrents 

We are certainly in the final phase of `networkx-metis` which involves lot of testing and code analysis. So, there are two things to be done for it, which requires administrative privilege and needs your attention. May any of you please

* Add `networkx/networkx-metis` repository over [travis-ci.org](https://travis-ci.org) and start build on Pull Requests.
* Add `networkx/networkx-metis` over [landscape.io](https://landscape.io) so that we can analyse small issues and [code smell](https://en.wikipedia.org/wiki/Code_smell).

**Comment by chebee7i** [comment]
I also enabled coveralls for metis and lemon.

**Comment by OrkoHunter** [comment]
Nice. And what about https://landscape.io/github/networkx/networkx-metis? Is it set?

**Comment by chebee7i** [comment]
Yep: https://landscape.io/github/networkx/networkx-metis
