### ISSUE TITLE
CI with appveyor for Windows

### ISSUE THREAD

**Issue by OrkoHunter** [networkx/networkx-metis#37]
Travis assures us that `networkx-metis` works perfectly on a Linux machine. We can also be sure for Mac. But since we are also supporting Windows and the ways of installation differs, I say that we use https://ci.appveyor.com for testing the package over windows. AppVeyor.com is a Continuous Integration service to build and run tests under Windows. [scikit-learn](https://github.com/scikit-learn/scikit-learn) uses it and they also depend upon Cython for wrapping.

**Comment by ysitu** [comment]
This is a very good idea. We should do the same thing for NetworkX core as well. AFAIK, Travis also [supports Mac OS X](http://docs.travis-ci.com/user/multi-os/). We can enable testing for that as well.

**Comment by MridulS** [comment]
Yes sounds like a good idea :) 
But I think there are some issues with Travis Mac environment for python https://github.com/travis-ci/travis-ci/issues/2320

**Comment by MridulS** [comment]
https://github.com/travis-ci/travis-ci/issues/2312

**Comment by OrkoHunter** [comment]
Yes there are issues with testing for osx. I made the required changes but it did not run. They clearly state that they are [not supporting multi-os](http://docs.travis-ci.com/user/multi-os/#We-are-not-currently-accepting-multi-OS-requests) for sometime

**Comment by OrkoHunter** [comment]
@chebee7i I made a ticket for the role permissions and it seems that there is already a facility for that. See http://www.appveyor.com/docs/team-setup

**Comment by chebee7i** [comment]
It looks like roles are tied to GitHub roles. http://www.appveyor.com/docs/team-setup#understanding-relationship-between-github-team-and-appveyor-role. Also, it seems like if I grant access to the NetworkX Developer team, then they have access to every project I put on appveyor, not just the NetworkX project (I could be reading this wrong, but when I look at the "Teams" in my Profile settings, there doesn't seem to be a way to assign to particular projects).
