### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by imehrdad2012** [networkx/networkx-metis#58]
Hello,

Unfortunately, I cannot install the package with pip:

0587364274:softbox mehrdadmoradi$ pip install networkx-metis
Collecting networkx-metis
  Could not find a version that satisfies the requirement networkx-metis (from versions: )
No matching distribution found for networkx-metis

how can I fix this?

**Comment by OrkoHunter** [comment]
Hey Mehrdad,

The problem with the installation with pip is because the package has not been uploaded to pypi (cc @hagberg @dschult). Sorry about that.
Please go through the installation instructions [here](https://github.com/networkx/networkx-metis#installation) and follow the `Installation from GitHub` part.

**Comment by imehrdad2012** [comment]
Thanks for the quick reply. I have previously installed on your package using the source on different machines. However,  I am not able to do it again on a fresh EI capitan OSX. I wonder if the following error is something from your side or mine? Thanks. 

metis/_metis.c:8599:37: warning: function '__Pyx_PyInt_As_long' is not needed and will not be emitted
      [-Wunneeded-internal-declaration]
          static CYTHON_INLINE long __Pyx_PyInt_As_long(PyObject *x) {
clang -bundle -undefined dynamic_lookup build/temp.macosx-10.11-x86_64-2.7/nxmetis/_metis.o -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -Lbuild/temp.macosx-10.11-x86_64-2.7 -lmetis -lgklib -lgklib -lmetis -o build/lib.macosx-10.11-x86_64-2.7/nxmetis/_metis.so
ld: in build/temp.macosx-10.11-x86_64-2.7/libgklib.a(error.o), section __DATA/__thread_bss extends beyond end of file, for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'clang' failed with exit status 1

**Comment by imehrdad2012** [comment]
I found the problem. The new Xcode (7.3) is the reason for this linking error. I have downgraded my xcode to 7.0, and everything works perfectly.

**Comment by Lamaun** [comment]
> Hey Mehrdad,
> 
> The problem with the installation with pip is because the package has not been uploaded to pypi (cc @hagberg @dschult). Sorry about that.
> Please go through the installation instructions [here](https://github.com/networkx/networkx-metis#installation) and follow the `Installation from GitHub` part.

Was there any reason for not uploading?
